version: '3.4'

services:
  nginx:
    build:
      context: ./docker/nginx
    read_only: true
    tty: true
    ports:
      - '8080:8080'
    volumes:
      - '/tmp'
      - 'drawer:/sock'
      - './public/:/var/www/html/public/:ro'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'

  php:
    build:
      context: ./docker/php
    tty: true
    volumes:
      - 'drawer:/sock'
      - './docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf'
      - './docker/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf'
      - './:/var/www/html/'

volumes:
  drawer: